package org.dutta.model;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

@ToString
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Data
@DynamoDBTable(tableName = "Payment")
public class Payment {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String paymentId;


    @DynamoDBAttribute
    private String orderId;
    @DynamoDBAttribute
    private Integer customerId;
    @DynamoDBAttribute
    private Integer sellerId;
    @DynamoDBAttribute
    private String paymentStatus;
    @DynamoDBAttribute
    private String paymentMethod;
    @DynamoDBAttribute
    private String paymentStatusNotes;



}
